book_ID=int(input("ENTER THE BOOK_ID:- "))
#TODO QUERY TO ADD THE book_ID INTO THE TABLE BOOK
bktitle=input("ENTER THE BOOK TITLE:- ")
#TODO QUERY TO ADD THE bktitle INTO THE TABLE BOOK
bkedition=input("ENTER THE BOOK EDITION:- ")
#TODO QUERY TO ADD THE bkedition INTO THE TABLE BOOK
bkauthor=input("ENTER THE NAME OF THE AUTHOR OF THE BOOK:- ")
#TODO QUERY TO ADD bkauthor INTO THE TABLE BOOK
bkpulisher=input("ENTER THE NAME OF THE NAME OF THE PUBLISHER OF THE BOOK:- ")
#TODO QUERY TO ADD bkpublisher INTO THE TABLE BOOK
bkcopies=int(input("ENTER THE NUMBER OF BOOKS PRESENT:- "))
#TODO QUERY TO ADD bkcopies INTO THE TABLE BOOK
bk_source=input("ENTER THE SOURCE OF THE BOOK:- ")
#TODO QUERY TO ADD bksource INTO THE TABLE BOOK
bk_cost=int(input("ENTER THE COST OF THE BOOK:- "))
#TODO QUERY TO ADD bk_cost INTO THE TABLE BOOK
bk_remarks=input("ENTER ANY REMARKS YOU WANT TO ADD FOR THIS BOOK:- ")
#TODO QUERY TO ADD bk_remarks INTO THE TABLE BOOK
