stud_ID=input("ENTER YOUR STUDENT ID:- ")
#TODO QUERY TO ADD THE stud_ID INTO THE TABLE STUDENT
stfname=input("ENTER YOUR FIRST NAME:- ")
#TODO QUERY TO ADD THE stfname INTO THE TABLE STUDENT
stlname=input("ENTER YOUR LAST NAME:- ")
#TODO QUERY TO ADD THE stlname INTO THE TABLE STUDENT
stcourse=input("ENTER YOUR COURSE:- ")
#TODO QUERY TO ADD THE stcourse INTO THE TABLE STUDENT
styear=input("ENTER THE YEAR YOU GOT ADMISSION IN:- ")
#TODO QUERY TO ADD THE styear INTO THE TABLE STUDENT
stcontact=int(input("ENTER YOUR CONTACT NUMBER:-"))
#TODO QUERY TO ADD THE stcontact INTO THE TABLE STUDENT
stage=int(input("ENTER YOUR AGE:-"))
#TODO QUERY TO ADD THE stage INTO THE TABLE STUDENT
stbirthdate=input("ENTER YOUR BIRTH DATE IN (YYYY-MM-DD) FORMAT:- ")
#TODO QUERY TO ADD THE stbirthdate INTO THE TABLE STUDENT
stgender=input("ENTER YOUR GENDER:- ")
#TODO QUERY TO ADD THE stgender INTO THE TABLE STUDENT
