staff_ID=int(input("ENTER YOUR STAFF_ID:- "))
#TODO QUERY TO ADD staff_ID INTO THE TABLE USERS
stffname=input("ENTER YOUR FIRST NAME:- ")
#TODO QUERY TO ADD THE stffname INTO THE TABLE USERS
stfflname=input("ENTER YOUR LAST NAME- ")
#TODO QUERY TO ADD THE stfflname INTO THT TABLE USERS
stffcontactnumber=input("ENTER YOUR CONTACT NUMBER:- ")
#TODO QUERY TO ADD THE stffcontactnumber INTO THE TABLE USERS
stfemail=input("ENTER YOUR EMAIL_ID:- ")
#TODO QUERY TO ADD THE stfemail INTO THE TABLE USERS
stfaddress=input("ENTER YOUR HOME ADDRESS:- ")
#TODO QUERY TO ADD THE stfaddress INTO THE TABLE USERS
stfpassword=input("ENTER YOUR PASSWORD FOR THE NEW ACCOUNT:- ")
#TODO QUERY TO ADD THE stfpassword INTO THE TABLE USERS
stftype=input("ON HOLD THIS IS JUST A PLACEHOLDER TEXT:- ")
#TODO QUERY TO ADD THE stftype INTO THE TABLE USERS
